### ISSUE TITLE
Hi Zhouhao

### ISSUE THREAD

**Issue by scheung38** [zhouhao27/ParseLoginDemo#1]
Thank you for sharing. May I ask how to launch it successfully?

Linkedin Framework and Libraries: missing libPods.a?

also I guess I need to create plist.info from developer.facebook.com:
FacebookAppID
FacebookDisplayName
URL types ?

Parse.setApplicationId("AppID", clientKey: "ClientId")
        PFFacebookUtils.initializeFacebook()

where AppID and ClientId are?

**Comment by zhouhao27** [comment]
You have to run pod install first. Please refer to cocoapods.

appid and clientid are from parse.com. You have to register and then create an application. Then you'll get those info under Settings.

**Comment by scheung38** [comment]
Thanks. Tried to install cocoapods but complains that ruby has to be greater than 2.0.0 but when tried to upgrade ruby there seems to be lots of libs missing?

**Comment by zhouhao27** [comment]
I’m using sudo gem install cocoapods to install.

What is your OS X version? Mine is 10.10.2. Maybe I upgraded the ruby by myself.

**Comment by scheung38** [comment]
sudo gem install cocoapods 
ERROR: Error installing cocoapods:
               cocoapods-trunk requires Ruby version >= 2.0.0 

But not sure how to upgrade Ruby?

**Comment by scheung38** [comment]
Hi again,

My OSX is also latest Yosemite 10.10.2 

and upgraded ruby so now it is :

$ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

ParseLoginDemo $ sudo gem install cocoapods
Successfully installed cocoapods-0.36.0
1 gem installed

so with upgraded cocoapods, and then inside project ParseLoginDemo directory:

 $pod install
/Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'cocoapods' (>= 0) among 154 total gem(s) (Gem::LoadError)
    from /Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:309:in`to_spec'
    from /Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Users/seb/.rbenv/versions/2.1.5/bin/pod:22:in`<main>'

after correction, now slightly better but

$pod install
-bash: /Users/seb/.rbenv/shims/pod: No such file or directory

Any idea?

**Comment by zhouhao27** [comment]
Please uninstall cocoapods and reinstall again. The run pod setup. Please refer to:

http://stackoverflow.com/questions/20819564/pod-not-found-after-install-pod-setup-returns-could-not-find-cocoapods

**Comment by scheung38** [comment]
Thanks will try.

Also where does that rfc1034 come from?

com.zeus.$(PRODUCT_NAME:rfc1034identifier)

**Comment by scheung38** [comment]
http://stackoverflow.com/questions/24018355/cocoapods-with-xcode-6-and-10-10-yosemite:

up vote
179
down vote
accepted
Open Xcode 6
Open Preferences
Click the Locations tab
Change the Command Line Tools version to Xcode 6.0
Uninstall cocoapods
$ sudo gem uninstall cocoapods
Uninstall xcodeproj $ sudo gem uninstall xcodeproj
Install xcodeproj
$ sudo gem install xcodeproj
Install cocoapods
$ sudo gem install cocoapods
Run pod --version to verify that it worked

But after trying I get

pod --version
/Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'cocoapods' (>= 0) among 154 total gem(s) (Gem::LoadError)
    from /Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:309:in`to_spec'
    from /Users/seb/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Users/seb/.rbenv/versions/2.1.5/bin/pod:22:in`<main>'

**Comment by scheung38** [comment]
ruby installation only version 2.1.5 was a success, if trying anywhere between 2.2.1 or 2.3.0-dev, both 

FAILED

Downloading openssl-1.0.1l.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/b2cf4d48fe5d49f240c61c9e624193a6f232b5ed0baf010681e725963c40d1d4
Installing openssl-1.0.1l...
Installed openssl-1.0.1l to /usr/local/var/rbenv/versions/2.3.0-dev

Cloning https://github.com/ruby/ruby.git...
Installing ruby-2.3.0-dev...

BUILD FAILED (OS X 10.10.2 using ruby-build 20150303)

Inspect or clean up the working tree at /var/folders/nv/4qz4kgk91rsd_28q18b_ljw00000gn/T/ruby-build.20150312161622.83128
Results logged to /var/folders/nv/4qz4kgk91rsd_28q18b_ljw00000gn/T/ruby-build.20150312161622.83128.log

SUCCESS:

Downloading ruby-2.1.5.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100
Installing ruby-2.1.5...
Installed ruby-2.1.5 to /usr/local/var/rbenv/versions/2.1.5
